FROM python:3.11-slim

WORKDIR /tmp/test-framework

ENV VENV /opt/venv
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONPATH /tmp/test-framework 

RUN apt-get update && apt-get install -y build-essential

RUN python3 -m venv ${VENV}
ENV PATH="${VENV}/bin:$PATH"

COPY dashboard /tmp/test-framework/dashboard

WORKDIR /tmp/test-framework/dashboard
RUN pip install -r requirements.txt

CMD ["python", "app.py"]
